apiVersion: v1
kind: Pod
metadata:
  name: cosign-keyless-signer
spec:
  # securityContext:
  #   runAsUser: 0   # 👈 FIXME run container as root for microdnf when using registry.access.redhat.com/ubi9/ubi-minimal
  imagePullSecrets:
    - name: mmortari-tarilabs-lm-evaluation-harness-pull-secret
  containers:
  - name: cosign
    image: registry.redhat.io/rhtas/cosign-rhel9:1.1.1 # instead of installing cosign into registry.access.redhat.com/ubi9/ubi-minimal
    env:
    - name: TUF_URL
      valueFrom:
        secretKeyRef:
          name: tas-demo-connection1
          key: TUF_URL
    - name: FULCIO_URL
      valueFrom:
        secretKeyRef:
          name: tas-demo-connection1
          key: FULCIO_URL
    command: ["/bin/sh","-c"]
    args:
      - |
        echo $TUF_URL
        echo $FULCIO_URL
        IMAGE=quay.io/mmortari/demo20251016-lmeh-olot@sha256:20f3b8da4f4ad1fb6d7210d318e2ab6b4f20b83ed29e89bf6dbc7d937f642002

        cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
        TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        echo "$TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .
        PAYLOAD_BASE64URL=$(echo "$TOKEN" | cut -d '.' -f2)
        # ignoring error from basenc command because old version requires padding which is optional for base64url
        PAYLOAD=$(echo "$PAYLOAD_BASE64URL" | basenc --base64url -d 2>/dev/null || true)
        OIDC_ISSUER=$(echo "$PAYLOAD" | sed -n 's/.*"iss":"\([^"]*\)".*/\1/p')
        echo "OIDC Issuer: $OIDC_ISSUER"

        echo "Signing image $IMAGE with FULCIO_URL $FULCIO_URL and my TOKEN"
        COSIGN_EXPERIMENTAL=1 cosign sign -y --fulcio-url=$FULCIO_URL --identity-token=$TOKEN $IMAGE
    volumeMounts:
    - name: sa-token
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    - name: docker-config
      mountPath: /home/.docker
  volumes:
  - name: sa-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          audience: "sigstore"  # this is important and it's coming from the securesign setup
          expirationSeconds: 600
  - name: docker-config
    secret:
      secretName: mmortari-tarilabs-lm-evaluation-harness-pull-secret
      items:
      - key: .dockerconfigjson
        path: config.json     # rename into config.json for Docker
  restartPolicy: Never
